# Listen address
listen: "127.0.53.53:53"

translation:
  default: "300:dada:feda:f443:ff::"
  prefixes:
    - prefix: "300:baba:cafa::"
      domains:
        - "com."
        - "net."
    - prefix: "300:6553:5::"
      domains:
        - "google.com."

forwarders:
  default:
    - 8.8.8.8:53
    - 1.1.1.1:53
  zones:
    - name: "com."
      upstreams:
        - 8.8.8.8:53
        - 1.1.1.1:53

# Prefix of mesh-net. 200::/7 (yggdrasil) by default
mesh-prefix: "200::/7"

# A complete prohibition on the return of A records
# Otherwise return A records with AAAA
strict-ipv6: yes

#If enabled, non-matced to mesh-prefix AAAA records will be returned if no A record exists. Disabled by default.
allow-fallback-aaaa: no 

# What to do with an "0.0.0.0" and [::] addresses
#   "ignore"  - treated like a regular address (i.e. 0.0.0.0 return as [prefix::], [::] - drop)
#               default behavior.
#   "process" - 0.0.0.0 translate to [::]. [::] return "as-is"
#   "discard" - discard this address
invalid-address: ignore

# Static addresses
static:
  "test.com" : 8.8.8.8
  "test2.com" : 8.8.8.8

# Cache timers. In minutes
cache:
    expiration: 5
    purge: 10